"""Kinisi protocol-v2 payloads, generated from firmware commands.json.

Do not edit this file manually; run tools/update-commands.py instead.
Transport framing, message IDs, and synchronization live in KinisiController.
"""

import struct
from enum import IntEnum


PROTOCOL_VERSION = (2, 1, 0)

INITIALIZE_MOTOR = 0x01
SET_MOTOR_SPEED = 0x02
STOP_MOTOR = 0x03
BRAKE_MOTOR = 0x04
INITIALIZE_MOTOR_CONTROLLER = 0x05
SET_MOTOR_TARGET_SPEED = 0x06
RESET_MOTOR_CONTROLLER = 0x07
GET_MOTOR_CONTROLLER_STATE = 0x08
DELETE_MOTOR_CONTROLLER = 0x09
SET_CONTROLLER_FREQUENCY = 0x0A
GET_CONTROLLER_FREQUENCY = 0x0B
INITIALIZE_ENCODER = 0x11
GET_ENCODER_VALUE = 0x12
START_ENCODER_ODOMETRY = 0x13
RESET_ENCODER_ODOMETRY = 0x14
STOP_ENCODER_ODOMETRY = 0x15
GET_ENCODER_ODOMETRY = 0x16
SET_ODOMETRY_FREQUENCY = 0x17
GET_ODOMETRY_FREQUENCY = 0x18
INITIALIZE_GPIO_PIN = 0x20
SET_GPIO_PIN_STATE = 0x21
GET_GPIO_PIN_STATE = 0x22
TOGGLE_GPIO_PIN_STATE = 0x23
SET_STATUS_LED_STATE = 0x25
TOGGLE_STATUS_LED_STATE = 0x26
INITIALIZE_MECANUM_PLATFORM = 0x30
INITIALIZE_OMNI_PLATFORM = 0x31
INITIALIZE_DIFFERENTIAL_PLATFORM = 0x32
SET_PLATFORM_VELOCITY = 0x40
START_PLATFORM_CONTROLLER = 0x41
SET_PLATFORM_TARGET_VELOCITY = 0x42
GET_PLATFORM_CURRENT_VELOCITY = 0x43
STOP_PLATFORM_CONTROLLER = 0x44
START_PLATFORM_ODOMETRY = 0x45
RESET_PLATFORM_ODOMETRY = 0x46
STOP_PLATFORM_ODOMETRY = 0x47
GET_PLATFORM_ODOMETRY = 0x48
BRAKE_PLATFORM = 0x49
COAST_PLATFORM = 0x4A
INIT = 0x70
ERROR = 0x7F
TIME_SYNC_REQUEST = 0x71
TIME_SYNC_RESPONSE = 0x72
READY = 0x73
SET_TIME_SYNC_INTERVAL = 0x74
GET_TIME_STATUS = 0x75
PING = 0x76
SET_HEARTBEAT_CONFIG = 0x77
GET_HEARTBEAT_CONFIG = 0x78
SUBSCRIBE_ODOMETRY = 0x79
UNSUBSCRIBE_ODOMETRY = 0x7A
ENCODER_ODOMETRY_EVENT = 0x7B
PLATFORM_ODOMETRY_EVENT = 0x7C
POLL_TELEMETRY = 0x7D


class ErrorCode(IntEnum):
    """Error codes returned by the shared controller ERROR message."""

    INCOMPATIBLE_PROTOCOL = 1
    INVALID_ARGUMENT = 2
    UNKNOWN_COMMAND = 3
    INVALID_LENGTH = 4
    MOTOR_OWNED = 5
    INTERNAL_ERROR = 6
    CLOCK_NOT_READY = 7
    TIME_SYNC_FAILED = 8
    ODOMETRY_NOT_INITIALIZED = 9
    SAMPLE_NOT_AVAILABLE = 10
    ENCODER_NOT_INITIALIZED = 11
    PLATFORM_NOT_INITIALIZED = 12
    MOTOR_NOT_INITIALIZED = 13
    CONTROLLER_NOT_INITIALIZED = 14
    INIT_REQUIRED = 15


ERROR_DESCRIPTIONS = {
    1: 'The requested protocol version is incompatible with this firmware.',
    2: 'A field is invalid, out of range, or inconsistent with the pending request.',
    3: 'The received command ID is not accepted by the controller.',
    4: 'The complete message has an invalid header or payload length.',
    5: 'The motor belongs to a platform; use the corresponding platform command.',
    6: 'The controller could not execute or encode the operation.',
    7: 'Initial clock setup is incomplete; wait for READY. Uptime mode also supports READY.',
    8: 'Initial time sync exhausted its attempts without a valid sample.',
    9: 'Odometry is not running; start odometry before requesting a measurement.',
    10: 'Odometry is running but has no measurement yet, including immediately after reset; retry after an update.',
    11: 'Initialize the encoder before reading it or starting encoder odometry.',
    12: 'Initialize a platform before performing this operation.',
    13: 'Initialize the motor before setting its speed.',
    14: 'Start or initialize the closed-loop controller before setting its target.',
    15: 'Send a valid INIT request before performing this connection-dependent operation.',
}


def _unpack_payload(fmt: str, payload: bytes) -> tuple:
    """Decode one exact payload rather than accepting a partial or extra frame."""
    expected = struct.calcsize(fmt)
    if len(payload) != expected:
        raise ValueError(f"Expected {expected} payload bytes, received {len(payload)}")
    return struct.unpack(fmt, payload)


class MotorControllerState:
    """The state of the controller for the specified motor.

    motor_index: Index of the motor with the controller.
    kp: Proportional constant of PID
    ki: Integral constant of PID
    kd: Derivative constant of PID
    target_speed: The target speed of the motor.
    current_speed: The current speed of the motor.
    error: The error of the motor.
    output: The output of the motor.
    """

    def __init__(self, motor_index: int, kp: float, ki: float, kd: float, target_speed: float, current_speed: float, error: float, output: float):
        """Store the fields of one controller payload."""
        self.motor_index = motor_index
        self.kp = kp
        self.ki = ki
        self.kd = kd
        self.target_speed = target_speed
        self.current_speed = current_speed
        self.error = error
        self.output = output

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 57

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<bddddddd', self.motor_index, self.kp, self.ki, self.kd, self.target_speed, self.current_speed, self.error, self.output))

    @classmethod
    def decode(cls, payload: bytes) -> 'MotorControllerState':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<bddddddd', payload))


class PlatformVelocity:
    """The velocity of the platform in meters per second.

    x: X component of platform velocity in meters per second
    y: Y component of platform velocity in meters per second
    t: Theta component of platform velocity in radians per second
    """

    def __init__(self, x: float, y: float, t: float):
        """Store the fields of one controller payload."""
        self.x = x
        self.y = y
        self.t = t

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 24

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<ddd', self.x, self.y, self.t))

    @classmethod
    def decode(cls, payload: bytes) -> 'PlatformVelocity':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<ddd', payload))


class PlatformOdometry:
    """The odometry of the platform in meters and radians.

    x: X component of platform odometry in meters
    y: Y component of platform odometry in meters
    t: Theta component of platform odometry in radians
    """

    def __init__(self, x: float, y: float, t: float):
        """Store the fields of one controller payload."""
        self.x = x
        self.y = y
        self.t = t

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 24

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<ddd', self.x, self.y, self.t))

    @classmethod
    def decode(cls, payload: bytes) -> 'PlatformOdometry':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<ddd', payload))


class InitResponse:
    """Packed 15-byte INIT response; firmware build ID is a Git revision, not a semantic
    release version.

    board_model: 1 Kinisi motor controller.
    board_major: Hardware revision major.
    board_minor: Hardware revision minor.
    board_patch: Hardware revision patch.
    protocol_major: Protocol version major.
    protocol_minor: Protocol version minor.
    protocol_patch: Protocol version patch.
    firmware_build_high: First eight hexadecimal digits of the firmware Git commit.
    firmware_build_low: Next eight hexadecimal digits of the firmware Git commit.
    """

    def __init__(self, board_model: int, board_major: int, board_minor: int, board_patch: int, protocol_major: int, protocol_minor: int, protocol_patch: int, firmware_build_high: int, firmware_build_low: int):
        """Store the fields of one controller payload."""
        self.board_model = board_model
        self.board_major = board_major
        self.board_minor = board_minor
        self.board_patch = board_patch
        self.protocol_major = protocol_major
        self.protocol_minor = protocol_minor
        self.protocol_patch = protocol_patch
        self.firmware_build_high = firmware_build_high
        self.firmware_build_low = firmware_build_low

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 15

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<BBBBBBBII', self.board_model, self.board_major, self.board_minor, self.board_patch, self.protocol_major, self.protocol_minor, self.protocol_patch, self.firmware_build_high, self.firmware_build_low))

    @classmethod
    def decode(cls, payload: bytes) -> 'InitResponse':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<BBBBBBBII', payload))


class TimeStatus:
    """Per-connection clock status.

    clock_mode: 0 uptime, 1 Unix wall time.
    clock_quality: 0 unready, 1 valid, 2 stale.
    interval_ms: Sync interval.
    last_sync_age_us: Elapsed since successful sync; zero in uptime or unready mode.
    """

    def __init__(self, clock_mode: int, clock_quality: int, interval_ms: int, last_sync_age_us: int):
        """Store the fields of one controller payload."""
        self.clock_mode = clock_mode
        self.clock_quality = clock_quality
        self.interval_ms = interval_ms
        self.last_sync_age_us = last_sync_age_us

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 14

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<BBIQ', self.clock_mode, self.clock_quality, self.interval_ms, self.last_sync_age_us))

    @classmethod
    def decode(cls, payload: bytes) -> 'TimeStatus':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<BBIQ', payload))


class EncoderOdometrySample:
    """Odometry state with controller-captured timestamp and clock metadata.

    timestamp_us: Measurement timestamp in selected clock domain.
    clock_mode: 0 uptime, 1 Unix wall time.
    clock_quality: 1 valid, 2 stale.
    angle: Encoder odometry radians.
    """

    def __init__(self, timestamp_us: int, clock_mode: int, clock_quality: int, angle: float):
        """Store the fields of one controller payload."""
        self.timestamp_us = timestamp_us
        self.clock_mode = clock_mode
        self.clock_quality = clock_quality
        self.angle = angle

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 18

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<QBBd', self.timestamp_us, self.clock_mode, self.clock_quality, self.angle))

    @classmethod
    def decode(cls, payload: bytes) -> 'EncoderOdometrySample':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<QBBd', payload))


class PlatformOdometrySample:
    """Odometry state with controller-captured timestamp and clock metadata.

    timestamp_us: Measurement timestamp in selected clock domain.
    clock_mode: 0 uptime, 1 Unix wall time.
    clock_quality: 1 valid, 2 stale.
    x: X meters.
    y: Y meters.
    t: Heading radians.
    """

    def __init__(self, timestamp_us: int, clock_mode: int, clock_quality: int, x: float, y: float, t: float):
        """Store the fields of one controller payload."""
        self.timestamp_us = timestamp_us
        self.clock_mode = clock_mode
        self.clock_quality = clock_quality
        self.x = x
        self.y = y
        self.t = t

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 34

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<QBBddd', self.timestamp_us, self.clock_mode, self.clock_quality, self.x, self.y, self.t))

    @classmethod
    def decode(cls, payload: bytes) -> 'PlatformOdometrySample':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<QBBddd', payload))


class HeartbeatConfig:
    """Per-connection watchdog settings.

    enabled: Enable monitoring; disabled initially for compatibility.
    timeout_ms: Monotonic receive timeout. Default 500 ms; send PING after at most timeout/5
    of idle time (100 ms with the default).
    """

    def __init__(self, enabled: bool, timeout_ms: int):
        """Store the fields of one controller payload."""
        self.enabled = enabled
        self.timeout_ms = timeout_ms

    @staticmethod
    def get_size() -> int:
        """Return the encoded payload size, excluding the message header."""
        return 5

    def encode(self) -> bytearray:
        """Encode every field using the packed little-endian wire layout."""
        return bytearray(struct.pack('<?I', self.enabled, self.timeout_ms))

    @classmethod
    def decode(cls, payload: bytes) -> 'HeartbeatConfig':
        """Decode exactly one payload; reject truncation and trailing bytes."""
        return cls(*_unpack_payload('<?I', payload))


class KinisiCommands:
    """Public command methods shared by transports implementing protocol v2."""

    def __init__(self):
        """Leave connection state and synchronization to the transport."""

    def _request(self, command: int, payload: bytes, expected_response_length: int) -> bytes:
        """Exchange a command payload and return its matching response payload."""
        raise NotImplementedError("A protocol-v2 transport must implement _request")

    def initialize_motor(self, motor_index: int, is_reversed: bool) -> None:
        """This command initializes a motor and prepares it for use. Rejected with MOTOR_OWNED
        if the motor is currently owned by an active platform (one of its wheels), so
        platform wheels are not reconfigured out from under the platform.

        motor_index: The index of the motor to initialize.
        is_reversed: Whether or not the motor is reversed.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED,
        INIT_REQUIRED.
        """
        payload = struct.pack('<B?', motor_index, is_reversed)
        result = self._request(INITIALIZE_MOTOR, payload, 0)

    def set_motor_speed(self, motor_index: int, pwm: float) -> None:
        """This command sets the speed of the specified motor in PWM. Rejected with MOTOR_OWNED
        if the motor is currently owned by an active platform (one of its wheels); use the
        platform velocity commands to drive platform wheels.

        motor_index: The index of the motor to set the speed for.
        pwm: The speed of the motor.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED,
        MOTOR_NOT_INITIALIZED, INIT_REQUIRED.
        """
        payload = struct.pack('<Bd', motor_index, pwm)
        result = self._request(SET_MOTOR_SPEED, payload, 0)

    def stop_motor(self, motor_index: int) -> None:
        """Coasts the motor to a stop: both H-bridge outputs are driven low, leaving the motor
        terminals open (high impedance) so it free-wheels and spins down gradually under its
        own friction. This also stops that motor's closed-loop speed controller if one is
        running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive
        the motor; to command the motor by target speed again you must re-initialize its
        controller. This is a single-motor command and is ignored if the motor is currently
        owned by an active platform (one of its wheels); to stop a platform, use
        STOP_PLATFORM_CONTROLLER, COAST_PLATFORM or BRAKE_PLATFORM instead. Use STOP_MOTOR
        for a soft, low-stress stop; use BRAKE_MOTOR when you need the motor to hold
        position and stop quickly.

        motor_index: The index of the motor to set the speed for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED.
        """
        payload = struct.pack('<B', motor_index)
        result = self._request(STOP_MOTOR, payload, 0)

    def brake_motor(self, motor_index: int) -> None:
        """Actively brakes the motor (short brake): both H-bridge outputs are driven high,
        shorting the motor terminals together so the motor's own back-EMF resists rotation
        and it stops quickly and holds position. This also stops that motor's closed-loop
        speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the
        PID loop cannot re-drive the motor; to command the motor by target speed again you
        must re-initialize its controller. This is a single-motor command and is ignored if
        the motor is currently owned by an active platform (one of its wheels); to brake a
        platform, use BRAKE_PLATFORM (or STOP_PLATFORM_CONTROLLER / COAST_PLATFORM) instead.
        Use BRAKE_MOTOR for a fast, holding stop; use STOP_MOTOR to let the motor coast
        freely instead.

        motor_index: The index of the motor to set the speed for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED.
        """
        payload = struct.pack('<B', motor_index)
        result = self._request(BRAKE_MOTOR, payload, 0)

    def initialize_motor_controller(self, motor_index: int, is_reversed: bool, encoder_index: int, is_encoder_reversed: bool, encoder_resolution: float, kp: float, ki: float, kd: float, integral_limit: float) -> None:
        """This command sets the controller for the specified motor. Rejected with MOTOR_OWNED
        if the motor is currently owned by an active platform (one of its wheels), so it
        cannot create a competing controller on a platform wheel.

        motor_index: The index of the motor to set the controller for.
        is_reversed: Whether or not the motor is reversed.
        encoder_index: The index of the encoder to use for the controller.
        is_encoder_reversed: Reverses the encoder counting direction, independently of the
        motor's is_reversed. For closed-loop control the encoder must report a positive
        measured speed when a positive speed is commanded (negative feedback); if the
        controller runs away, flip this flag.
        encoder_resolution: Encoder resolution in ticks per revolution. The value can not be
        negative or zero.
        kp: Proportional constant of PID
        ki: Integral constant of PID
        kd: Derivative constant of PID
        integral_limit: Integral limit of PID controller. The value can not be negative or
        zero. If the value is zero or negative, the integral limit is disabled.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED,
        INIT_REQUIRED.
        """
        payload = struct.pack('<B?B?ddddd', motor_index, is_reversed, encoder_index, is_encoder_reversed, encoder_resolution, kp, ki, kd, integral_limit)
        result = self._request(INITIALIZE_MOTOR_CONTROLLER, payload, 0)

    def set_motor_target_speed(self, motor_index: int, speed: float) -> None:
        """This command sets the target speed for the specified motor in radians. Rejected with
        MOTOR_OWNED if the motor is currently owned by an active platform (one of its
        wheels); use SET_PLATFORM_TARGET_VELOCITY to drive platform wheels.

        motor_index: The index of the motor to set the target velocity for.
        speed: The speed of the motor.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED,
        CONTROLLER_NOT_INITIALIZED, INIT_REQUIRED.
        """
        payload = struct.pack('<Bd', motor_index, speed)
        result = self._request(SET_MOTOR_TARGET_SPEED, payload, 0)

    def reset_motor_controller(self, motor_index: int) -> None:
        """This command resets the closed-loop controller for the specified motor: it clears
        the accumulated PID state (integrator windup, derivative history and internal
        output) and re-zeros the target speed, while keeping the controller running with its
        existing tuning (kp/ki/kd). Use it to recover from integrator windup or to bring a
        motor cleanly to a stop without deleting and re-initializing the controller. No
        effect if no controller is running for that motor, and ignored if the motor is
        currently owned by an active platform (one of its wheels).

        motor_index: The index of the motor to reset the controller for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED,
        INIT_REQUIRED.
        """
        payload = struct.pack('<B', motor_index)
        result = self._request(RESET_MOTOR_CONTROLLER, payload, 0)

    def get_motor_controller_state(self, motor_index: int) -> MotorControllerState:
        """This command gets the state of the controller for the specified motor.

        motor_index: The index of the motor to get the state for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', motor_index)
        result = self._request(GET_MOTOR_CONTROLLER_STATE, payload, MotorControllerState.get_size())
        return MotorControllerState.decode(result)

    def delete_motor_controller(self, motor_index: int) -> None:
        """This command deletes the controller for the specified motor. Rejected with
        MOTOR_OWNED if the motor is currently owned by an active platform (one of its
        wheels); use STOP_PLATFORM_CONTROLLER to stop the platform controller instead.

        motor_index: The index of the motor to delete the controller for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, MOTOR_OWNED,
        INIT_REQUIRED.
        """
        payload = struct.pack('<B', motor_index)
        result = self._request(DELETE_MOTOR_CONTROLLER, payload, 0)

    def set_controller_frequency(self, frequency: int) -> None:
        """This command sets the global update frequency (in Hz) of the closed-loop motor
        controller task. All motor controllers share a single control loop, so this
        frequency is global and affects every currently running controller as well as any
        created afterwards; the PID sampling time is updated to match. The requested value
        is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by
        the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms =
        1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid
        and ignored. Defaults to 10 Hz (100 ms) at start-up.

        frequency: The controller update frequency in Hz. Valid range 1 to 1000 Hz; values
        outside are clamped, and 0 is ignored.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<H', frequency)
        result = self._request(SET_CONTROLLER_FREQUENCY, payload, 0)

    def get_controller_frequency(self) -> int:
        """This command retrieves the current global update frequency (in Hz) of the
        closed-loop motor controller task.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(GET_CONTROLLER_FREQUENCY, payload, 2)
        return _unpack_payload('<H', result)[0]

    def initialize_encoder(self, encoder_index: int, encoder_resolution: float, is_reversed: bool) -> None:
        """This command initializes an encoder and prepares it for use.

        encoder_index: The index of the encoder to initialize.
        encoder_resolution: Encoder resolution in ticks per revolution. The value can not be
        negative or zero.
        is_reversed: Whether or not the encoder is reversed.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<Bd?', encoder_index, encoder_resolution, is_reversed)
        result = self._request(INITIALIZE_ENCODER, payload, 0)

    def get_encoder_value(self, encoder_index: int) -> int:
        """This command retrieves the current value of the encoder.

        encoder_index: The index of the encoder to retrieve the value for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR,
        ENCODER_NOT_INITIALIZED, INIT_REQUIRED.
        """
        payload = struct.pack('<B', encoder_index)
        result = self._request(GET_ENCODER_VALUE, payload, 2)
        return _unpack_payload('<H', result)[0]

    def start_encoder_odometry(self, encoder_index: int) -> None:
        """This command starts the odometry calculation for the specified encoder.

        encoder_index: The index of the encoder to start the odometry calculation for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY, ENCODER_NOT_INITIALIZED.
        """
        payload = struct.pack('<B', encoder_index)
        result = self._request(START_ENCODER_ODOMETRY, payload, 0)

    def reset_encoder_odometry(self, encoder_index: int) -> None:
        """This command resets the odometry calculation for the specified encoder.

        encoder_index: The index of the encoder to reset the odometry calculation for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', encoder_index)
        result = self._request(RESET_ENCODER_ODOMETRY, payload, 0)

    def stop_encoder_odometry(self, encoder_index: int) -> None:
        """This command stops the odometry calculation for the specified encoder.

        encoder_index: The index of the encoder to stop the odometry calculation for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', encoder_index)
        result = self._request(STOP_ENCODER_ODOMETRY, payload, 0)

    def get_encoder_odometry(self, encoder_index: int) -> EncoderOdometrySample:
        """This command retrieves the odometry of the specified encoder.

        encoder_index: The index of the encoder to retrieve the odometry for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY, ODOMETRY_NOT_INITIALIZED, SAMPLE_NOT_AVAILABLE.
        """
        payload = struct.pack('<B', encoder_index)
        result = self._request(GET_ENCODER_ODOMETRY, payload, EncoderOdometrySample.get_size())
        return EncoderOdometrySample.decode(result)

    def set_odometry_frequency(self, frequency: int) -> None:
        """This command sets the global update frequency (in Hz) of the odometry task. A single
        odometry task integrates all encoder and platform odometry, so this frequency is
        global. The requested value is clamped to the supported range of 1 to 1000 Hz (the
        1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to
        the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are
        1000/N Hz. A value of 0 is invalid and ignored. Defaults to 20 Hz (50 ms) at
        start-up. Rejected if the resulting calculation period exceeds half of any active
        subscription interval on either transport.

        frequency: The odometry update frequency in Hz. Valid range 1 to 1000 Hz; values
        outside are clamped, and 0 is ignored.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<H', frequency)
        result = self._request(SET_ODOMETRY_FREQUENCY, payload, 0)

    def get_odometry_frequency(self) -> int:
        """This command retrieves the current global update frequency (in Hz) of the odometry
        task.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(GET_ODOMETRY_FREQUENCY, payload, 2)
        return _unpack_payload('<H', result)[0]

    def initialize_gpio_pin(self, pin_number: int, mode: int) -> None:
        """This command initializes a digital pin and prepares it for use.

        pin_number: The number of the pin to initialize.
        mode: Set digital pin as input or output. Modes: 0 = INPUT_PULLDOWN, 1 =
        INPUT_PULLUP, 2 = INPUT_NOPULL, 3 = OUTPUT.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<BB', pin_number, mode)
        result = self._request(INITIALIZE_GPIO_PIN, payload, 0)

    def set_gpio_pin_state(self, pin_number: int, state: int) -> None:
        """This command sets the specified pin to a state.

        pin_number: The number of the pin to set to a state.
        state: The state of the pin. 0 = LOW, 1 = HIGH.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<BB', pin_number, state)
        result = self._request(SET_GPIO_PIN_STATE, payload, 0)

    def get_gpio_pin_state(self, pin_number: int) -> int:
        """This command gets the state of the specified pin.

        pin_number: The number of the pin to get the state for.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', pin_number)
        result = self._request(GET_GPIO_PIN_STATE, payload, 1)
        return _unpack_payload('<B', result)[0]

    def toggle_gpio_pin_state(self, pin_number: int) -> None:
        """This command toggles the specified pin.

        pin_number: The number of the pin to toggle.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', pin_number)
        result = self._request(TOGGLE_GPIO_PIN_STATE, payload, 0)

    def set_status_led_state(self, state: int) -> None:
        """This command sets the status LED to a state.

        state: The state of the status LED. 0 = OFF, 1 = ON.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', state)
        result = self._request(SET_STATUS_LED_STATE, payload, 0)

    def toggle_status_led_state(self) -> None:
        """This command toggles the status LED.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(TOGGLE_STATUS_LED_STATE, payload, 0)

    def initialize_mecanum_platform(self, is_reversed_0: bool, is_reversed_1: bool, is_reversed_2: bool, is_reversed_3: bool, is_encoder_reversed_0: bool, is_encoder_reversed_1: bool, is_encoder_reversed_2: bool, is_encoder_reversed_3: bool, length: float, width: float, wheels_diameter: float, encoder_resolution: float) -> None:
        """This command initializes a mecanum (4-wheel) platform and prepares it for use. It
        uses motor and encoder indices 0, 1, 2 and 3 (one per wheel), which correspond to
        the is_reversed_0..3 and is_encoder_reversed_0..3 parameters. All four motor slots
        are occupied by this platform.

        is_reversed_0: Determines if motor 0 is reversed.
        is_reversed_1: Determines if motor 1 is reversed.
        is_reversed_2: Determines if motor 2 is reversed.
        is_reversed_3: Determines if motor 3 is reversed.
        is_encoder_reversed_0: Reverses encoder 0 counting direction, independently of motor
        0's is_reversed_0. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        is_encoder_reversed_1: Reverses encoder 1 counting direction, independently of motor
        1's is_reversed_1. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        is_encoder_reversed_2: Reverses encoder 2 counting direction, independently of motor
        2's is_reversed_2. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        is_encoder_reversed_3: Reverses encoder 3 counting direction, independently of motor
        3's is_reversed_3. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        length: Length of the platform in meters.
        width: Width of the platform in meters.
        wheels_diameter: Diameter of the robot wheels in meters.
        encoder_resolution: Encoder resolution in ticks per revolution. The value can not be
        negative. If platform does not have encoders, the value should be set to zero.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<????????dddd', is_reversed_0, is_reversed_1, is_reversed_2, is_reversed_3, is_encoder_reversed_0, is_encoder_reversed_1, is_encoder_reversed_2, is_encoder_reversed_3, length, width, wheels_diameter, encoder_resolution)
        result = self._request(INITIALIZE_MECANUM_PLATFORM, payload, 0)

    def initialize_omni_platform(self, is_reversed_0: bool, is_reversed_1: bool, is_reversed_2: bool, is_encoder_reversed_0: bool, is_encoder_reversed_1: bool, is_encoder_reversed_2: bool, wheels_diameter: float, robot_radius: float, encoder_resolution: float) -> None:
        """This command initializes an omni (3-wheel) platform and prepares it for use. It uses
        motor and encoder indices 0, 1 and 2 (one per wheel), which correspond to the
        is_reversed_0..2 and is_encoder_reversed_0..2 parameters. Motor index 3 is not used
        by this platform and stays free for other purposes.

        is_reversed_0: Determines if motor 0 is reversed.
        is_reversed_1: Determines if motor 1 is reversed.
        is_reversed_2: Determines if motor 2 is reversed.
        is_encoder_reversed_0: Reverses encoder 0 counting direction, independently of motor
        0's is_reversed_0. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        is_encoder_reversed_1: Reverses encoder 1 counting direction, independently of motor
        1's is_reversed_1. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        is_encoder_reversed_2: Reverses encoder 2 counting direction, independently of motor
        2's is_reversed_2. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        wheels_diameter: Diameter of the robot wheels in millimeters.
        robot_radius: Distance berween the center of the robot and the center of the wheels
        in millimeters.
        encoder_resolution: Encoder resolution in ticks per revolution. The value can not be
        negative. If platform does not have encoders, the value should be set to zero.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<??????ddd', is_reversed_0, is_reversed_1, is_reversed_2, is_encoder_reversed_0, is_encoder_reversed_1, is_encoder_reversed_2, wheels_diameter, robot_radius, encoder_resolution)
        result = self._request(INITIALIZE_OMNI_PLATFORM, payload, 0)

    def initialize_differential_platform(self, is_reversed_0: bool, is_reversed_1: bool, is_encoder_reversed_0: bool, is_encoder_reversed_1: bool, wheel_diameter: float, wheel_base: float, encoder_resolution: float) -> None:
        """This command initializes a differential (2-wheel) platform and prepares it for use.
        It uses motor and encoder index 0 for the left wheel and index 1 for the right
        wheel, which correspond to the is_reversed_0/1 and is_encoder_reversed_0/1
        parameters. Motor indices 2 and 3 are not used by this platform and stay free for
        other purposes.

        is_reversed_0: Determines if motor 0 is reversed.
        is_reversed_1: Determines if motor 1 is reversed.
        is_encoder_reversed_0: Reverses encoder 0 counting direction, independently of motor
        0's is_reversed_0. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        is_encoder_reversed_1: Reverses encoder 1 counting direction, independently of motor
        1's is_reversed_1. Set so the closed-loop feedback is negative (flip if the wheel
        runs away when given a target speed).
        wheel_diameter: Diameter of the robot wheels in meters.
        wheel_base: Distance between the two wheels in meters.
        encoder_resolution: Encoder resolution in ticks per revolution. The value can not be
        negative. If platform does not have encoders, the value should be set to zero.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<????ddd', is_reversed_0, is_reversed_1, is_encoder_reversed_0, is_encoder_reversed_1, wheel_diameter, wheel_base, encoder_resolution)
        result = self._request(INITIALIZE_DIFFERENTIAL_PLATFORM, payload, 0)

    def set_platform_velocity(self, x: float, y: float, t: float) -> None:
        """This command sets the velocity for the platform in PWM.

        x: X component of platform velocity in PWM
        y: Y component of platform velocity in PWM
        t: Theta component of platform velocity in PWM

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR,
        PLATFORM_NOT_INITIALIZED, INIT_REQUIRED.
        """
        payload = struct.pack('<ddd', x, y, t)
        result = self._request(SET_PLATFORM_VELOCITY, payload, 0)

    def start_platform_controller(self, kp: float, ki: float, kd: float, integral_limit: float) -> None:
        """This command sets the controller for the platform.

        kp: Proportional constant of PID
        ki: Integral constant of PID
        kd: Derivative constant of PID
        integral_limit: Integral limit of PID controller. The value can not be negative or
        zero. If the value is zero or negative, the integral limit is disabled.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR,
        PLATFORM_NOT_INITIALIZED, INIT_REQUIRED.
        """
        payload = struct.pack('<dddd', kp, ki, kd, integral_limit)
        result = self._request(START_PLATFORM_CONTROLLER, payload, 0)

    def set_platform_target_velocity(self, x: float, y: float, t: float) -> None:
        """This command set the target velocity for the platform in meters per second.

        x: X component of platform velocity in meters per second
        y: Y component of platform velocity in meters per second
        t: Theta component of platform velocity in radians per second

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR,
        PLATFORM_NOT_INITIALIZED, CONTROLLER_NOT_INITIALIZED, INIT_REQUIRED.
        """
        payload = struct.pack('<ddd', x, y, t)
        result = self._request(SET_PLATFORM_TARGET_VELOCITY, payload, 0)

    def get_platform_current_velocity(self) -> PlatformVelocity:
        """This command gets the current velocity of the platform in meters per second.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(GET_PLATFORM_CURRENT_VELOCITY, payload, PlatformVelocity.get_size())
        return PlatformVelocity.decode(result)

    def stop_platform_controller(self) -> None:
        """This command stops the controller for the platform.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR.
        """
        payload = struct.pack('<')
        result = self._request(STOP_PLATFORM_CONTROLLER, payload, 0)

    def start_platform_odometry(self) -> None:
        """This command starts the odometry calculation for the platform.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY, PLATFORM_NOT_INITIALIZED.
        """
        payload = struct.pack('<')
        result = self._request(START_PLATFORM_ODOMETRY, payload, 0)

    def reset_platform_odometry(self) -> None:
        """This command resets the odometry calculation for the platform.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(RESET_PLATFORM_ODOMETRY, payload, 0)

    def stop_platform_odometry(self) -> None:
        """This command stops the odometry calculation for the platform.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(STOP_PLATFORM_ODOMETRY, payload, 0)

    def get_platform_odometry(self) -> PlatformOdometrySample:
        """This command retrieves the odometry of the platform in meters and radians.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY, ODOMETRY_NOT_INITIALIZED, SAMPLE_NOT_AVAILABLE.
        """
        payload = struct.pack('<')
        result = self._request(GET_PLATFORM_ODOMETRY, payload, PlatformOdometrySample.get_size())
        return PlatformOdometrySample.decode(result)

    def brake_platform(self) -> None:
        """This command actively brakes all of this platform's wheel motors (short brake) so
        they resist motion and hold position, and stops the platform velocity controller if
        it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop
        platform control). Motors used outside this platform are not affected. The motors
        resist motion until a new command is issued.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR.
        """
        payload = struct.pack('<')
        result = self._request(BRAKE_PLATFORM, payload, 0)

    def coast_platform(self) -> None:
        """This command lets all of this platform's wheel motors coast freely (high impedance)
        so they spin down without resistance, and stops the platform velocity controller if
        it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop
        platform control). Motors used outside this platform are not affected. The motors
        spin down without resistance.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR.
        """
        payload = struct.pack('<')
        result = self._request(COAST_PLATFORM, payload, 0)

    def init(self, sdk_type: int, client_version_major: int, client_version_minor: int, client_version_patch: int, protocol_major: int, protocol_minor: int, protocol_patch: int, client_capabilities: int) -> InitResponse:
        """Exchange identity and start per-connection clock initialization. Wait for READY
        before odometry. Clients with wall-clock capability answer controller
        TIME_SYNC_REQUEST messages; other clients use uptime. Repeating INIT restarts clock
        setup without altering motor state.

        sdk_type: 0 unknown, 1 Python, 2 JavaScript, 3 Arduino.
        client_version_major: Client library major version.
        client_version_minor: Client library minor version.
        client_version_patch: Client library patch version.
        protocol_major: Client protocol major version.
        protocol_minor: Minimum required protocol minor version.
        protocol_patch: Client protocol patch version, informational; compatibility is
        determined by major and minor.
        client_capabilities: Bit 0 (1): valid wall-clock time available. Bit 1 (2): client
        supports telemetry subscriptions. Combine as 3 for both; 0 for neither. Other bits
        must be zero. Declaring support does not start time synchronization or create
        subscriptions.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR,
        INCOMPATIBLE_PROTOCOL, TIME_SYNC_FAILED.
        """
        payload = struct.pack('<BBBBBBBB', sdk_type, client_version_major, client_version_minor, client_version_patch, protocol_major, protocol_minor, protocol_patch, client_capabilities)
        result = self._request(INIT, payload, InitResponse.get_size())
        return InitResponse.decode(result)

    def set_time_sync_interval(self, interval_ms: int) -> None:
        """Set independent time-sync refresh interval for this connection. Default 30000 ms.

        interval_ms: Periodic resynchronization interval in milliseconds.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<I', interval_ms)
        result = self._request(SET_TIME_SYNC_INTERVAL, payload, 0)

    def get_time_status(self) -> TimeStatus:
        """Read this connection's clock mode, quality, interval and age.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(GET_TIME_STATUS, payload, TimeStatus.get_size())
        return TimeStatus.decode(result)

    def ping(self) -> None:
        """Refresh connection activity and receive an empty ACK. Any structurally valid client
        command also refreshes activity; malformed frames do not.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(PING, payload, 0)

    def set_heartbeat_config(self, enabled: bool, timeout_ms: int) -> None:
        """Configure this session watchdog after READY. Timeout coasts all motors, clears
        subscriptions and requires a new INIT before further operations. Disabling also
        removes this session subscriptions. INIT resets to disabled, 500 ms.

        enabled: Enable monitoring; disabled initially for compatibility.
        timeout_ms: Monotonic receive timeout. Default 500 ms; send PING after at most
        timeout/5 of idle time (100 ms with the default).

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY.
        """
        payload = struct.pack('<?I', enabled, timeout_ms)
        result = self._request(SET_HEARTBEAT_CONFIG, payload, 0)

    def get_heartbeat_config(self) -> HeartbeatConfig:
        """Read this session watchdog configuration.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<')
        result = self._request(GET_HEARTBEAT_CONFIG, payload, HeartbeatConfig.get_size())
        return HeartbeatConfig.decode(result)

    def subscribe_odometry(self, source: int, interval_ms: int) -> None:
        """Publish the latest completed sample using the requested scheduling interval without
        rounding it to calculation ticks. Delivery is subject to transport capacity and task
        scheduling. Requires READY, an enabled heartbeat and running odometry. Replaces an
        existing subscription for this source. Interval must be at least twice the
        calculation period. No renewal is needed. Stop/reset of calculation pauses samples
        until fresh measurements exist; unsubscribe, INIT, disconnect or watchdog timeout
        removes subscriptions.

        source: 0 through 3 select encoder odometry; 4 selects platform odometry.
        interval_ms: Delivery interval, independent of calculation scheduling.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY, ODOMETRY_NOT_INITIALIZED.
        """
        payload = struct.pack('<BI', source, interval_ms)
        result = self._request(SUBSCRIBE_ODOMETRY, payload, 0)

    def unsubscribe_odometry(self, source: int) -> None:
        """Remove this source subscription; succeeds if already absent. Does not stop odometry
        calculation.

        source: 0 through 3 select encoder odometry; 4 selects platform odometry.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED.
        """
        payload = struct.pack('<B', source)
        result = self._request(UNSUBSCRIBE_ODOMETRY, payload, 0)

    def poll_telemetry(self) -> None:
        """I2C master service request. Allows at most one due odometry event before its empty
        ACK, so the master can clock out telemetry without waiting indefinitely when no
        sample is available. USB clients receive events automatically and do not need this
        command.

        Controller errors: INVALID_LENGTH, INVALID_ARGUMENT, INTERNAL_ERROR, INIT_REQUIRED,
        CLOCK_NOT_READY.
        """
        payload = struct.pack('<')
        result = self._request(POLL_TELEMETRY, payload, 0)

